Repository openshift/cincinnati, pull requests merged in 2018-11, with the labels that each got.

#7 cincinnati: update for new spec details
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  docs/design/cincinnati.md
  graph-builder/src/graph.rs
  graph-builder/src/registry.rs
Labels: size/M

#4 graph-builder: switch to using dkregistry and implement authenticated requests
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/src/config.rs
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  graph-builder/src/registry.rs
  graph-builder/src/release.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
Labels: lgtm, size/XXL

#10 docs: fix typo
  README.md
Labels: size/XS

#13 graph-builder/registry: refactor uses
  graph-builder/src/registry.rs
Labels: lgtm, size/M

#12 graph-builder: improve logging output
  graph-builder/src/registry.rs
Labels: size/XS

#15 graph-builder: normalize imports
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  graph-builder/src/registry.rs
Labels: lgtm, size/M

#16 *: update metadata file name
  docs/design/openshift.md
  graph-builder/src/registry.rs
Labels: lgtm, size/XS

#17 graph-builder/registry: use stream instead of loop
  graph-builder/src/graph.rs
  graph-builder/src/registry.rs
Labels: lgtm, size/L
