Repository openshift/cincinnati, pull requests merged in 2018-12, with the labels that each got.

#18 dist/Dockerfile: bump rustc and log dkregistry errors
  dist/Dockerfile
Labels: lgtm, size/XS

#19 add scripts for CI/CD integration
  dist/Dockerfile
  dist/build_deploy.sh
  dist/pr_check.sh
Labels: lgtm, size/M

#21 use another build image that does not require special permissions on project files
  dist/build_deploy.sh
  dist/pr_check.sh
Labels: lgtm, size/XS

#22 dist: optimize build script and Dockerfile
  dist/Dockerfile
  dist/build_deploy.sh
  dist/commons.sh
  dist/pr_check.sh
Labels: size/M

#23 introduce openshift template
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.secret.yaml
  dist/openshift/cincinnati.yaml
Labels: size/L

#25 dist/rust: 1.30.0 -> 1.31.0
  dist/build/Dockerfile
Labels: size/XS

#27 move loglevel to the config map
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
Labels: size/S

#28 remove openshift secret since it is managed outhise of this repo
  dist/openshift/cincinnati.secret.yaml
Labels: lgtm, size/XS

#30 graph-builder: use high-level tokio API
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/src/main.rs
  graph-builder/src/registry.rs
Labels: size/S

#32 registry/assemble-metadata: change filename according to the ocp-release repo
  graph-builder/src/registry.rs
Labels: lgtm, size/XS
