Repository openshift/cincinnati, pull requests merged in 2019-05, with the labels that each got.

#94 openshift: consistently rename metrics -> status
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#97 cargo: update prometheus to 0.6.0
  Cargo.lock
  graph-builder/Cargo.toml
  policy-engine/Cargo.toml
Labels: approved, lgtm, size/S

#98 commons: add docstrings and enable missing_docs lint
  commons/src/config.rs
  commons/src/de.rs
  commons/src/errors.rs
  commons/src/lib.rs
Labels: approved, lgtm, size/S

#99 policy-engine: add docstrings and enable missing_docs lint
  policy-engine/src/config/cli.rs
  policy-engine/src/config/file.rs
  policy-engine/src/config/options.rs
  policy-engine/src/main.rs
Labels: approved, lgtm, size/S

#89 cincinnati: namespace all metrics according to application
  Cargo.lock
  commons/Cargo.toml
  commons/src/errors.rs
  commons/src/lib.rs
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/src/status.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/metrics.rs
Labels: approved, lgtm, size/L

#100 OWNERS_ALIASES: add shiywang
  OWNERS_ALIASES
Labels: approved, lgtm

#95 graph-builder: eliminate possible rwlock starvation
  Cargo.lock
  dist/openshift/cincinnati.yaml
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/src/status.rs
Labels: approved, lgtm, size/L

#60 OWNERS_ALIASES: prevent unnecessary notifications
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#101 commons: rename error metrics
  commons/src/errors.rs
Labels: approved, lgtm, size/XS

#88 cincinnati/plugins: add plugins catalog and configuration
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/catalog.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/mod.rs
Labels: approved, lgtm, size/L

#102 *: Move from com.openshift.upgrades to io.openshift.upgrades
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  docs/user/graph-builder-configuration.md
  graph-builder/src/config/settings.rs
  graph-builder/tests/net/quay_io/mod.rs
  quay/src/v1/manifest.rs
  quay/tests/net/mod.rs
Labels: approved, lgtm, size/S

#104 policy-engine && graph-builder: fix and switch to 2018 edition
  .gitignore
  cincinnati/src/lib.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/mod.rs
  commons/src/lib.rs
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  graph-builder/src/registry.rs
  graph-builder/src/status.rs
  graph-builder/tests/net/quay_io/mod.rs
  policy-engine/Cargo.toml
  policy-engine/src/graph.rs
  policy-engine/src/openapi.rs
  quay/src/v1/mod.rs
Labels: approved, lgtm, size/M

#106 *: refactors, docstrings, formatting, clippy fixes
  cincinnati/src/lib.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/interface.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/mod.rs
  commons/src/errors.rs
  graph-builder/src/config/cli.rs
  graph-builder/src/config/file.rs
  graph-builder/src/config/options.rs
  graph-builder/src/graph.rs
  graph-builder/src/registry.rs
  graph-builder/src/status.rs
  graph-builder/tests/net/quay_io/mod.rs
  policy-engine/src/config/cli.rs
  policy-engine/src/config/file.rs
  policy-engine/src/config/options.rs
  policy-engine/src/graph.rs
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/L

#107 dist: update to Rust toolchain 1.34.2
  dist/build/Dockerfile
  dist/openshift-release/Dockerfile.builder
Labels: approved, lgtm, size/XS

#103 docs/design/cincinnati: Remove edges instead of removing nodes
  docs/design/cincinnati.md
  docs/design/figures/cincinnati-bad-node.svg
  docs/design/figures/cincinnati-components.svg
  docs/design/figures/cincinnati-initial.svg
  docs/design/figures/cincinnati-patch-node.svg
  docs/design/figures/openshift-4.svg
  docs/design/figures/openshift-5.svg
  docs/design/openshift.md
Labels: approved, lgtm, size/L

#105 plugins/edge_add_remove: add special previous/next value for removing all edges in that direction
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  graph-builder/src/graph.rs
Labels: approved, lgtm, size/L

#108 hack/graph.sh: Add a script for rendering Cincinnati to DOT
  docs/design/cincinnati.md
  hack/graph.sh
Labels: approved, lgtm, size/M

#112 hack/graph: Drop URI argument from the example
  hack/graph.sh
Labels: approved, lgtm, size/XS

#109 add some unit test enhancement and fix wrong function name
  commons/src/lib.rs
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/S

#110 rename file pr_check.sh to cargo_test.sh
  dist/cargo_test.sh
  dist/pr_check.sh
Labels: approved, lgtm, size/L
