Repository openshift/cincinnati, pull requests merged in 2019-09, with the labels that each got.

#149 cincinnati: add maplit, simplify testcase
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/plugins/internal/node_remove.rs
Labels: approved, lgtm, size/M

#150 OWNERS: +wking +vrutkovs -shiywang
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#148 readme: update example curl call with channel name and expected output
  README.md
Labels: approved, lgtm, size/S

#156 Update code per rustfmt recommendations
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  graph-builder/src/config/file.rs
Labels: approved, lgtm, size/S

#151 channel_filter: return GraphErrors instead of FailedPluginExecution
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/macros.rs
  commons/src/errors.rs
  policy-engine/src/graph.rs
Labels: approved, lgtm, size/S

#159 cincinnati/src/plugins/internal/metadata_fetch_quay: Fix "nohting" -> "nothing" typo
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
Labels: approved, lgtm, size/XS

#154 policy-engine: set custom buckets for v1_graph_serve_duration_seconds
  policy-engine/src/graph.rs
Labels: approved, lgtm, size/XS

#152 Create a metric to track duration of upstream scrapes
  Cargo.lock
  cincinnati/Cargo.toml
  commons/Cargo.toml
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  policy-engine/Cargo.toml
Labels: approved, lgtm, size/M

#158 graph-builder/registry: require the manifestref
  graph-builder/src/registry.rs
Labels: approved, lgtm, size/M

#155 graph-builder/registry: ApplicationJson content-type workaround
  graph-builder/src/registry.rs
Labels: approved, lgtm, size/M

#157 Dockerfile: use rustup and install 3 Rust versions
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm, size/S

#160 policy-engine/src/graph: remove extra line to make rustfmt happy
  policy-engine/src/graph.rs
Labels: approved, lgtm, size/XS

#162 Dockerfile: Update to rust 1.38
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm, size/XS

#164 cincinnati/src/plugins/macros: make rustfmt 1.38 happy
  cincinnati/src/plugins/macros.rs
Labels: approved, lgtm, size/XS

#161 openshift: enforce CPU limits on each container
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/M
