Repository openshift/cincinnati, pull requests merged in 2019-11, with the labels that each got.

#177 dockerfile: use rust 1.39
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm, size/XS

#179 cincinnati: expose customizable testgraph generator
  cincinnati/src/lib.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/cincinnati_graph_fetch.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/mod.rs
Labels: approved, lgtm, size/L

#178 plugins/internal/cincinnati_graph_fetch: Fix "ghis" -> "this" typo
  cincinnati/src/plugins/internal/cincinnati_graph_fetch.rs
Labels: approved, lgtm, size/XS

#180 add multi-arch support
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/catalog.rs
  cincinnati/src/plugins/internal/arch_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/mod.rs
  cincinnati/src/plugins/macros.rs
  commons/src/errors.rs
  dist/openshift/cincinnati.configmap.yaml
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  graph-builder/src/registry.rs
  graph-builder/tests/images/build-n-push-buildah.sh
  graph-builder/tests/images/test-public-multiarch-manual-0.0.0/Dockerfile
  graph-builder/tests/images/test-public-multiarch-manual-0.0.0/release-metadata
  graph-builder/tests/images/test-public-multiarch-manual-0.0.1/Dockerfile
  graph-builder/tests/images/test-public-multiarch-manual-0.0.1/release-metadata
  graph-builder/tests/images/test-public-multiarch-manual-0.0.2_amd64/.arch
  graph-builder/tests/images/test-public-multiarch-manual-0.0.2_amd64/Dockerfile
  graph-builder/tests/images/test-public-multiarch-manual-0.0.2_amd64/release-metadata
  graph-builder/tests/images/test-public-multiarch-manual-0.0.2_arm64/.arch
  graph-builder/tests/images/test-public-multiarch-manual-0.0.2_arm64/Dockerfile
  graph-builder/tests/images/test-public-multiarch-manual-0.0.2_arm64/release-metadata
  graph-builder/tests/images/test-public-multiarch-manual-0.0.3_amd64/.arch
  graph-builder/tests/images/test-public-multiarch-manual-0.0.3_amd64/Dockerfile
  graph-builder/tests/images/test-public-multiarch-manual-0.0.3_amd64/release-metadata
  graph-builder/tests/images/test-public-multiarch-manual-0.0.3_arm64/.arch
  graph-builder/tests/images/test-public-multiarch-manual-0.0.3_arm64/Dockerfile
  graph-builder/tests/images/test-public-multiarch-manual-0.0.3_arm64/release-metadata
  graph-builder/tests/images/test-public-multiarch-manual-0.0.4_amd64/.arch
  graph-builder/tests/images/test-public-multiarch-manual-0.0.4_amd64/Dockerfile
  graph-builder/tests/images/test-public-multiarch-manual-0.0.4_amd64/release-metadata
  graph-builder/tests/net/quay_io/mod.rs
  policy-engine/src/config/settings.rs
Labels: approved, lgtm, size/XL

#181 dist/openshift: don't require 'version' param in policy-engine
  dist/openshift/cincinnati.configmap.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#182 dist/openshift: inline configmap in template
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/M
