Repository openshift/cincinnati, pull requests merged in 2019-08, with the labels that each got.

#135 docs: update CLI flags in README
  README.md
Labels: approved, lgtm, size/XS

#137 cincinnati/src/plugins/internal/edge_add_remove: Mention labels in leading comment
  cincinnati/src/plugins/internal/edge_add_remove.rs
Labels: approved, lgtm, size/XS

#129 policy-engine: add TOML configuration for policy plugins
  cincinnati/src/plugins/catalog.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/mod.rs
  commons/src/config.rs
  graph-builder/src/config/cli.rs
  graph-builder/src/config/file.rs
  graph-builder/src/config/options.rs
  graph-builder/src/config/settings.rs
  policy-engine/src/config/cli.rs
  policy-engine/src/config/file.rs
  policy-engine/src/config/mod.rs
  policy-engine/src/config/options.rs
  policy-engine/src/config/settings.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/L

#139 switch from try_from crate to std variant
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/mod.rs
Labels: approved, lgtm, size/M

#133 introduce asynchronous plugin processing
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/catalog.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/macros.rs
  cincinnati/src/plugins/mod.rs
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  graph-builder/src/status.rs
  policy-engine/src/config/file.rs
  policy-engine/src/config/settings.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/XXL

#142 fix compiler warnings with version 1.37.0 -- includes a rust-protoc bump and code regeneration
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/catalog.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/interface.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  graph-builder/src/status.rs
  policy-engine/src/config/settings.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/metrics.rs
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/L

#140 policy-engine/graph: split query params into at most 2 parts
  commons/src/errors.rs
  policy-engine/src/graph.rs
Labels: approved, kind/bug, lgtm, size/M

#145 dockerfile: update to latest stable toolchain (1.37.0)
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm, size/XS

#141 policy-engine/metrics: don't use a global registry
  Cargo.lock
  commons/Cargo.toml
  commons/src/lib.rs
  commons/src/metrics.rs
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  graph-builder/src/status.rs
  policy-engine/src/main.rs
  policy-engine/src/metrics.rs
Labels: approved, lgtm, size/L

#146 cargo: update mockito to 0.20.0
  Cargo.lock
  commons/Cargo.toml
  policy-engine/Cargo.toml
Labels: approved, lgtm, size/XXL

#147 cincinnati: fix and switch to Rust edition 2018
  cincinnati/Cargo.toml
  cincinnati/src/plugins/catalog.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
Labels: approved, lgtm, size/S

#138 extract graph-fetcher code from the policy-engine into an internal plugin
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/catalog.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/cincinnati_graph_fetch.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/mod.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/macros.rs
  cincinnati/src/plugins/mod.rs
  commons/src/errors.rs
  policy-engine/Cargo.toml
  policy-engine/src/config/file.rs
  policy-engine/src/config/settings.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/XL
