Repository openshift/cincinnati, pull requests merged in 2019-04, with the labels that each got.

#77 dist: update to Rust toolchain 1.33.0
  dist/build/Dockerfile
  dist/openshift-release/Dockerfile.builder
Labels: approved, lgtm, size/XS

#78 commons: list missing parameters in error message
  commons/src/errors.rs
  commons/src/lib.rs
  policy-engine/src/graph.rs
Labels: approved, lgtm, size/M

#69 graph-builder: add support for configuration file
  Cargo.lock
  cincinnati/Cargo.toml
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
  docs/user/graph-builder-configuration.md
  graph-builder/Cargo.toml
  graph-builder/src/config.rs
  graph-builder/src/config/cli.rs
  graph-builder/src/config/file.rs
  graph-builder/src/config/mod.rs
  graph-builder/src/config/options.rs
  graph-builder/src/config/settings.rs
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/tests/fixtures/sample-config.toml
Labels: approved, lgtm, size/XL

#83 openshift: use tcpSocket for policy-engine probes
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/S

#80 graph-builder: expose liveness status
  dist/openshift/cincinnati.yaml
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/src/metrics.rs
  graph-builder/src/status.rs
Labels: approved, lgtm, size/L

#82 graph-builder: expose readiness status
  dist/openshift/cincinnati.yaml
  graph-builder/src/main.rs
  graph-builder/src/status.rs
Labels: approved, lgtm, size/M

#79 cincinnati,policy-engine: add channel filter plugin and activate it
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/mod.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/macros.rs
  cincinnati/src/plugins/mod.rs
  policy-engine/src/graph.rs
Labels: approved, lgtm, size/XL

#84 openshift/policy-engine: require "channel" as a mandatory client parameter
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/S

#86 dist: bump toolchain to 1.34
  Cargo.lock
  dist/build/Dockerfile
  dist/openshift-release/Dockerfile.builder
Labels: approved, lgtm, size/XS

#87 quay: tweak read credentials logic
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  quay/src/lib.rs
Labels: approved, lgtm, size/M

#85 dist/template: fix YAML indentation
  dist/openshift-release/Dockerfile.builder
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
  dist/prow_yaml_lint.sh
Labels: approved, lgtm, size/L

#91 ci: add EPEL repo for yamllint
  dist/openshift-release/Dockerfile.builder
Labels: approved, size/XS

#90 Cargo/deps: bump dkregistry
  Cargo.lock
  graph-builder/Cargo.toml
Labels: approved, lgtm, size/M

#93 dist/cincinnati: fix status port variable
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS
