Repository openshift/cincinnati, pull requests merged in 2019-06, with the labels that each got.

#111 improve tests around the QuayMetadataFetch plugin
  cincinnati/Cargo.toml
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  graph-builder/tests/images/test-labels-private-manual-0.0.0
  graph-builder/tests/images/test-labels-private-manual-0.0.1
  graph-builder/tests/images/test-labels-private-manual-0.0.2
  graph-builder/tests/images/test-labels-private-manual-0.0.3
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/L

#115 dist/openshift-release/Dockerfile: remove image alias
  dist/openshift-release/Dockerfile.builder
Labels: approved, size/XS

#114 dist: unify and cleanup Dockerfiles, refactor scripts, enable private-net-tests
  README.md
  dist/Dockerfile.build/Dockerfile
  dist/Dockerfile.deploy/Dockerfile
  dist/build/Dockerfile
  dist/build_deploy.sh
  dist/cargo_test.sh
  dist/commons.sh
  dist/openshift-release/Dockerfile.builder
  dist/pr_check.sh
Labels: approved, lgtm, size/L

#119 hack,dist: move pr_check.sh and update README.md
  README.md
  dist/build.sh
  dist/cargo_test.sh
  hack/run-all-tests.sh
Labels: approved, lgtm, size/M

#121 add build-n-push script mentioned in README
  graph-builder/tests/images/build-n-push.sh
Labels: approved, lgtm, size/S

#117 policy-engine/graph: log served errors
  policy-engine/src/graph.rs
Labels: approved, lgtm, size/XS

#124 dist: add a Fedora-based container for fedora-infra
  .dockerignore
  dist/fedora-infra/Dockerfile
Labels: approved, lgtm, size/S

#126 cincinnati/plugins: require and derive Debug on plugins
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/mod.rs
Labels: approved, lgtm, size/S

#125 cargo: update prometheus to 0.7
  Cargo.lock
  commons/Cargo.toml
  commons/src/lib.rs
  commons/src/testing.rs
  graph-builder/Cargo.toml
  graph-builder/src/status.rs
  policy-engine/Cargo.toml
  policy-engine/src/metrics.rs
Labels: approved, lgtm, size/XXL

#123 *: bump actix/actix-web to 0.8.3/1.0.2
  Cargo.lock
  cincinnati/src/plugins/interface.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  commons/Cargo.toml
  commons/src/errors.rs
  commons/src/lib.rs
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  graph-builder/src/status.rs
  graph-builder/tests/mod.rs
  graph-builder/tests/net/quay_io/mod.rs
  policy-engine/Cargo.toml
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/metrics.rs
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/XXL

#128 policy-engine/openapi: rewrite paths after adding parameters + tests
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/M

#127 cincinnati/plugins/edge_add_remove: change, document, and test label precedence
  cincinnati/src/plugins/internal/edge_add_remove.rs
Labels: approved, lgtm, size/L
