Repository openshift/cincinnati, pull requests merged in 2019-02, with the labels that each got.

#55 graph-builder/registry: don't enforce HTTPS
  Cargo.lock
  commons/src/lib.rs
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/registry.rs
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/L

#56 Revert "*: rename payload -> image"
  cincinnati/src/lib.rs
  docs/design/cincinnati.md
  docs/design/openshift.md
  graph-builder/src/registry.rs
  policy-engine/src/openapiv3.json
Labels: approved, lgtm, size/M

#57 Cargo: bump dkregistry-rs (respect system CA certs)
  Cargo.lock
  graph-builder/Cargo.toml
Labels: approved, lgtm, size/M

#54 graph-builder: fetch quay labels conditionally
  graph-builder/src/config.rs
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/metadata.rs
  graph-builder/src/registry.rs
  graph-builder/tests/net/quay_io/mod.rs
  quay/src/v1/mod.rs
Labels: approved, lgtm, size/L

#48 graph-builder: process the release/previous/next labels
  cincinnati/src/lib.rs
  graph-builder/src/graph.rs
  graph-builder/src/registry.rs
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/L

#59 graph-builder: untangle the run-loop
  graph-builder/src/graph.rs
Labels: approved, lgtm, size/M

#58 commons: add custom errors with JSON responses
  Cargo.lock
  commons/Cargo.toml
  commons/src/errors.rs
  commons/src/lib.rs
  docs/design/cincinnati.md
  graph-builder/src/graph.rs
  policy-engine/src/graph.rs
  policy-engine/src/openapiv3.json
Labels: approved, lgtm, size/L

#50 cincinnati: add plugin-interface, code, and plugins; rewire the graph-builder to use plugins
  Cargo.lock
  README.md
  cincinnati/Cargo.toml
  cincinnati/build.rs
  cincinnati/src/lib.rs
  cincinnati/src/plugins/external/mod.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/interface.proto
  cincinnati/src/plugins/interface.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/mod.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/mod.rs
  commons/src/errors.rs
  graph-builder/src/config.rs
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/metadata.rs
  graph-builder/src/registry.rs
  graph-builder/tests/net/quay_io/mod.rs
  policy-engine/Cargo.toml
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
Labels: approved, lgtm, size/XXL

#61 Add label to cincinnati service
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#62 Correction: Add labels field and move actual label inside it
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS
