Repository openshift/cincinnati, pull requests merged in 2019-01, with the labels that each got.

#34 *: add files for (proper) openshift/release integration
  OWNERS
  OWNERS_ALIASES
  dist/openshift-release/Dockerfile.builder
Labels: lgtm, size/M

#37 OWNERS*: fix typo and make Luca an approver
  OWNERS
  OWNERS_ALIASES
Labels: size/XS

#11 add tests for `fetch_releases` pulling test images from quay.io
  README.md
  dist/build/Dockerfile
  dist/build_deploy.sh
  dist/commons.sh
  dist/pr_check.sh
  graph-builder/Cargo.toml
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/src/registry.rs
  graph-builder/src/release.rs
  graph-builder/tests/images/test-emptyfirsttag-public-manual-0.0.0/Dockerfile
  graph-builder/tests/images/test-emptyfirsttag-public-manual-0.0.0/EMPTY
  graph-builder/tests/images/test-emptyfirsttag-public-manual-0.0.1
  graph-builder/tests/images/test-emptyfirsttag-public-manual-0.0.2
  graph-builder/tests/images/test-nojson-public-manual-0.0.0/Dockerfile
  graph-builder/tests/images/test-private-manual-0.0.0/Dockerfile
  graph-builder/tests/images/test-private-manual-0.0.0/release-metadata_0.json
  graph-builder/tests/images/test-private-manual-0.0.0/release-metadata_1.json
  graph-builder/tests/images/test-private-manual-0.0.1/Dockerfile
  graph-builder/tests/images/test-private-manual-0.0.1/release-metadata
  graph-builder/tests/images/test-public-manual-0.0.0
  graph-builder/tests/images/test-public-manual-0.0.1
  graph-builder/tests/mod.rs
  graph-builder/tests/net/mod.rs
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/L

#33 cargo: update to latest env_logger (0.6.0)
  Cargo.lock
  graph-builder/Cargo.toml
  policy-engine/Cargo.toml
Labels: approved, lgtm, size/S

#35 graph-builder: cache release metadata lookups
  graph-builder/src/graph.rs
  graph-builder/src/registry.rs
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/L

#38 *: introduce path-namespace CLI argument
  Cargo.lock
  Cargo.toml
  commons/Cargo.toml
  commons/src/lib.rs
  graph-builder/Cargo.toml
  graph-builder/src/config.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  policy-engine/Cargo.toml
  policy-engine/src/config.rs
  policy-engine/src/main.rs
Labels: approved, lgtm, size/M

#41 *: bugfix and refactor prefix semantics
  commons/src/lib.rs
  graph-builder/src/config.rs
  graph-builder/src/main.rs
  policy-engine/src/config.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
Labels: approved, lgtm, size/M

#29 bump dkregistry and adapt to API changes
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/src/lib.rs
  graph-builder/src/registry.rs
Labels: approved, lgtm, size/XXL

#40 policy-engine: add OpenAPI spec and endpoint
  Cargo.lock
  policy-engine/Cargo.toml
  policy-engine/src/main.rs
  policy-engine/src/openapi.rs
  policy-engine/src/openapiv3.json
Labels: approved, lgtm, size/L

#43 adds PE_PATH_PREFIX param to the template
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#44 openshift: fix liveness and readyness probes
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#20 hack,README: add quickstart-container script
  README.md
  hack/quickstart-container.sh
Labels: approved, lgtm, size/M

#42 graph-builder: log update completion
  cincinnati/src/lib.rs
  graph-builder/src/graph.rs
Labels: approved, lgtm, size/S

#45 cincinnati: check for mandatory parameters in client query
  Cargo.lock
  commons/Cargo.toml
  commons/src/lib.rs
  graph-builder/src/config.rs
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  policy-engine/src/config.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/openapi.rs
Labels: approved, lgtm, size/L

#47 cincinnati: add Partial{,Eq} to Graph
  cincinnati/src/lib.rs
Labels: approved, lgtm, size/L

#46 quay: introduce a quay.io client library
  Cargo.lock
  Cargo.toml
  dist/pr_check.sh
  quay/Cargo.toml
  quay/src/lib.rs
  quay/src/v1/manifest.rs
  quay/src/v1/mod.rs
  quay/src/v1/tag.rs
  quay/tests/mod.rs
  quay/tests/net/mod.rs
  quay/tests/net/private.rs
Labels: approved, lgtm, size/L

#51 graph-builder: fetch and add labels to releases and refactor for testability
  Cargo.lock
  cincinnati/src/lib.rs
  graph-builder/Cargo.toml
  graph-builder/src/config.rs
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/registry.rs
  graph-builder/tests/images/test-labels-public-manual-0.0.0
  graph-builder/tests/images/test-labels-public-manual-0.0.1
  graph-builder/tests/images/test-labels-public-manual-0.0.2/Dockerfile
  graph-builder/tests/images/test-labels-public-manual-0.0.2/release-metadata_0.json
  graph-builder/tests/images/test-labels-public-manual-0.0.2/release-metadata_1.json
  graph-builder/tests/images/test-labels-public-manual-0.0.3/Dockerfile
  graph-builder/tests/images/test-labels-public-manual-0.0.3/release-metadata_0.json
  graph-builder/tests/images/test-labels-public-manual-0.0.3/release-metadata_1.json
  graph-builder/tests/net/quay_io/mod.rs
  quay/src/lib.rs
Labels: approved, lgtm, size/L

#52 dist/pr_check: add missing `commons` crate
  dist/pr_check.sh
Labels: approved, lgtm, size/XS

#53 policy-engine: add basic tests for graph endpoint
  Cargo.lock
  policy-engine/Cargo.toml
  policy-engine/src/config.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
Labels: approved, lgtm, size/M
