Repository openshift/cincinnati, pull requests merged in 2019-03, with the labels that each got.

#63 Add prometheus port to the containers and services
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/S

#64 Fix long status port names
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#66 docs: add instructions for inspecting the graph
  docs/design/cincinnati.md
Labels: approved, lgtm, size/M

#65 Use default port numbers, add specific app labels to services
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/S

#67 Policy engine: Publish Prometheus metrics on all interfaces inside Pod
  dist/openshift/cincinnati.configmap.yaml
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#68 Use template parameters for status ports
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/S

#71 policy-engine: minor appstate cleanup
  policy-engine/src/main.rs
Labels: approved, lgtm, size/XS

#72 graph-builder: instrument and expose graph metrics
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/src/metrics.rs
Labels: approved, lgtm, size/L

#73 cargo: update prometheus to 0.5
  Cargo.lock
  graph-builder/Cargo.toml
  policy-engine/Cargo.toml
Labels: approved, lgtm, size/M

#70 graph-builder/tests: fix building net-private tests
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/S

#75 graph-builder: use sha256 in payload if available
  graph-builder/src/registry.rs
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/M

#76 commons: make options parsers string-generic
  commons/src/lib.rs
Labels: approved, lgtm, size/S
