Repository openshift/cincinnati, pull requests merged in 2019-10, with the labels that each got.

#163 Add cincinnati_*_build_info metric with git commit label
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/src/build.rs
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  policy-engine/Cargo.toml
  policy-engine/src/build.rs
  policy-engine/src/main.rs
Labels: approved, lgtm, size/L

#165 graph-builder/src/graph: update bucket values for graph_upstream_scrapes_duration
  graph-builder/src/graph.rs
Labels: approved, lgtm, size/XS

#166 Add prow_rustfmt helper to run rustfmt
  README.md
  dist/prow_rustfmt.sh
Labels: approved, lgtm, size/S

#167 cincinnati/src/plugins/internal/channel_filter: Expose all channels
  cincinnati/src/plugins/internal/channel_filter.rs
Labels: approved, lgtm, size/S

#169 add app-sre as approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#170 commons: export errors HTTP code in metrics
  commons/src/errors.rs
Labels: approved, lgtm, size/XS

#168 Add scripts for e2e tests
  hack/e2e_collect.sh
  hack/e2e_compare.sh
Labels: approved, lgtm, size/M

#172 Revert "Add scripts for e2e tests"
  hack/e2e_collect.sh
  hack/e2e_compare.sh
Labels: approved, lgtm, size/M

#173 hack/graph: Port graph.sh for 🍎
  hack/graph.sh
Labels: approved, lgtm, size/S

#175 Added rrati to app-sre OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
