Repository openshift/cincinnati, pull requests merged in 2020-02, with the labels that each got.

#195 bump dkregistry-rs, futures, and all related dependencies; use async/await syntax for asynchronous code where possible
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/internal/arch_filter.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/cincinnati_graph_fetch.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
  cincinnati/src/plugins/mod.rs
  commons/Cargo.toml
  commons/src/errors.rs
  commons/src/metrics.rs
  commons/src/testing.rs
  graph-builder/Cargo.toml
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  graph-builder/src/registry.rs
  graph-builder/src/status.rs
  graph-builder/tests/e2e/mod.rs
  graph-builder/tests/net/quay_io/mod.rs
  policy-engine/Cargo.toml
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  policy-engine/src/openapi.rs
  quay/Cargo.toml
  quay/src/v1/manifest.rs
  quay/src/v1/mod.rs
  quay/src/v1/tag.rs
  quay/tests/net/mod.rs
  quay/tests/net/private.rs
Labels: approved, lgtm, size/XXL

#206 graph-builder/registry: asynchronously assemble image metadata
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/src/lib.rs
  graph-builder/src/registry.rs
Labels: approved, lgtm, size/L

#209 template: fix a typo in default value for graph-builder
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#210 dist/Dockerfile.build/Dockerfile: Install protobuf-compiler
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm, size/XS

#198 Adding justfile and adding instructions to make local development easier
  Justfile
  docs/developer/developing.md
Labels: approved, lgtm, size/L

#189 Updating the example in traversal with a real one
  docs/design/cincinnati.md
Labels: approved, lgtm, size/M

#174 graph-builder/registry: concurrent tag processing
  Cargo.lock
  dist/openshift/cincinnati.yaml
  graph-builder/Cargo.toml
  graph-builder/src/config/options.rs
  graph-builder/src/config/settings.rs
  graph-builder/src/graph.rs
  graph-builder/src/main.rs
  graph-builder/src/registry.rs
  graph-builder/tests/e2e/mod.rs
  graph-builder/tests/e2e/testdata/a-amd64.json
  graph-builder/tests/e2e/testdata/test-amd64.json
  graph-builder/tests/net/quay_io/mod.rs
Labels: approved, lgtm, size/XL

#213 template: update GB mem limit
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#212 e2e: use multistage dockerfile to prepare e2e image with artifacts
  dist/Dockerfile.build/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
  hack/e2e.sh
Labels: approved, lgtm, size/S

#211 Dockerfile.deploy: use multistage docker build
  dist/Dockerfile.build/Dockerfile
  dist/Dockerfile.deploy/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
  hack/e2e.sh
Labels: approved, lgtm, size/S

#218 Dockerfiles: use uppercase AS so that CI would replace these correctly
  dist/Dockerfile.deploy/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
Labels: approved, lgtm, size/XS

#217 Dockerfile: rename base image in multistage builds
  dist/Dockerfile.deploy/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
Labels: approved, lgtm, size/XS

#220 fix stage build after multistage rework
  dist/Dockerfile.deploy/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
  dist/build.sh
  dist/build_deploy.sh
  dist/commons.sh
Labels: approved, lgtm, size/S

#221 Increasing the maximum Policy-engine memory limit to 512Mi
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#222 build_deploy.sh: don't create temporary release dir
  dist/build_deploy.sh
Labels: approved, lgtm, size/S

#223 build_deploy: fix docker build CLI syntax
  dist/build_deploy.sh
Labels: approved, lgtm, size/XS

#216 e2e: set RUST_BACKTRACE in e2e tests and handle missing git commit data
  dist/Dockerfile.deploy/Dockerfile
  dist/openshift/cincinnati.yaml
  graph-builder/src/graph.rs
  hack/e2e.sh
  policy-engine/src/main.rs
Labels: approved, lgtm, size/M

#208 Removing the extern as we do not need it
  cincinnati/src/lib.rs
  commons/src/lib.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/tests/net/quay_io/mod.rs
  policy-engine/src/build.rs
  policy-engine/src/graph.rs
  policy-engine/src/main.rs
  quay/src/lib.rs
Labels: approved, lgtm, size/M

#214 Doc changes for net-private tests
  README.md
  docs/developer/developing.md
Labels: approved, lgtm, size/M

#224 graph-builder: move registry into an internal plugin
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/src/config/cli.rs
  graph-builder/src/config/mod.rs
  graph-builder/src/config/settings.rs
  graph-builder/src/graph.rs
  graph-builder/src/lib.rs
  graph-builder/src/main.rs
  graph-builder/src/plugins/mod.rs
  graph-builder/src/plugins/release_scrape_dockerv2/mod.rs
  graph-builder/src/plugins/release_scrape_dockerv2/plugin.rs
  graph-builder/src/plugins/release_scrape_dockerv2/registry/mod.rs
  graph-builder/src/plugins/release_scrape_dockerv2/registry/network_tests.rs
  graph-builder/src/release.rs
  graph-builder/src/tests/mod.rs
  graph-builder/tests/mod.rs
  graph-builder/tests/net/mod.rs
Labels: approved, lgtm, size/XXL

#215 Changing the HTTP response of readiness probe to 503 when not available
  graph-builder/src/status.rs
Labels: approved, lgtm, size/XS

#230 e2e: wait for default serviceaccount to appear
  hack/e2e.sh
Labels: approved, lgtm, size/XS

#229 graph-builder/tests/e2e: make sorting algorithm (hopefully) fully predictable
  commons/src/testing.rs
  graph-builder/tests/e2e/mod.rs
Labels: approved, lgtm, size/L

#226 graph-builder: add plugin to fetch openshift/cincinnati-graph-data from github
  Cargo.lock
  cincinnati/src/lib.rs
  graph-builder/Cargo.toml
  graph-builder/src/plugins/github_openshift_secondary_metadata_scraper/github_v3.rs
  graph-builder/src/plugins/github_openshift_secondary_metadata_scraper/mod.rs
  graph-builder/src/plugins/github_openshift_secondary_metadata_scraper/plugin.rs
  graph-builder/src/plugins/mod.rs
Labels: approved, lgtm, size/XL

#231 graph-builder: add plugin to parse openshift/cincinnati-graph-data
  Cargo.lock
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/node_remove.rs
  commons/src/testing.rs
  dist/prow_yaml_lint.sh
  graph-builder/Cargo.toml
  graph-builder/src/main.rs
  graph-builder/src/plugins/mod.rs
  graph-builder/src/plugins/openshift_secondary_metadata_parser/mod.rs
  graph-builder/src/plugins/openshift_secondary_metadata_parser/plugin.rs
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.1.1.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.1.10.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.2.0-rc.5.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.2.0.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.2.1.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.2.11-s390x.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.2.11.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.2.13-s390x.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.3.0-rc.0.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.3.0-rc.3.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/4.3.1.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/blocked-edges/_OWNERS
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/_OWNERS
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/candidate-4.2.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/candidate-4.3.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/fast-4.2.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/fast-4.3.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/prerelease-4.1.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/prerelease-4.2.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/stable-4.0.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/stable-4.1.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/stable-4.2.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/channels/stable-4.3.yaml
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/cincinnati-graph-data/raw/metadata.json
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/graph-gb-raw.json
  graph-builder/src/plugins/openshift_secondary_metadata_parser/test_fixtures/20200220.104838/graph-gb-with-quay-metadata.json
Labels: approved, lgtm, size/XXL
