Repository openshift/cincinnati, pull requests merged in 2020-03, with the labels that each got.

#242 dist/openshift: adapt to recent secret changes
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#240 graph_fetch: reuse clients when contacting graph-builder
  cincinnati/src/plugins/internal/cincinnati_graph_fetch.rs
Labels: approved, lgtm, size/S

#243 dist/openshift: migrate graph-builder to toml config
  dist/openshift/cincinnati.yaml
  graph-builder/src/config/file.rs
  graph-builder/src/config/options.rs
  graph-builder/src/config/settings.rs
  hack/e2e.sh
  policy-engine/src/config/file.rs
Labels: approved, lgtm, size/L

#244 e2e: allow redefining pull secret location
  dist/Dockerfile.e2e/Dockerfile
  hack/e2e.sh
Labels: approved, lgtm, size/S

#245 settings: use occurrences notation for file settings
  commons/src/de.rs
  dist/openshift/cincinnati.yaml
  graph-builder/src/config/cli.rs
  graph-builder/src/config/file.rs
  policy-engine/src/config/cli.rs
  policy-engine/src/config/file.rs
Labels: approved, lgtm, size/S

#246 dist/openshift/cincinnati: fix registry credentials path
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm, size/XS

#228 cargo_test: run `cargo kcov` to collect coverage in unittests
  dist/Dockerfile.build/Dockerfile
  dist/cargo_test.sh
Labels: approved, lgtm, size/M

#247 graph-builder,policy-engine: log cincinnati crate
  graph-builder/src/main.rs
  policy-engine/src/main.rs
Labels: approved, lgtm, size/XS

#233 graph-builder/plugins/github scraper: add token authorization handling
  Justfile
  cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/mod.rs
  cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs
  dist/openshift/cincinnati.yaml
  hack/e2e.sh
Labels: approved, lgtm, size/M

#248 e2e: reconfigure monitoring operator to scrape Cincinnati
  dist/Dockerfile.e2e/Dockerfile
  dist/openshift/observability.yaml
  graph-builder/Cargo.toml
  graph-builder/tests/mod.rs
  graph-builder/tests/slo/mod.rs
  hack/e2e.sh
Labels: approved, lgtm, size/L

#241 Sort releases by Alphabetical prior to sorting by release number.
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/plugin.rs
Labels: approved, lgtm, ok-to-test, size/XS

#251 Dockerfile.build: bump rust to 1.42.0
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm

#252 cincinnati: trace adding EdgeIndexes
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/graph_builder/release.rs
Labels: approved, lgtm

#255 dist/cargo_test: properly propagate test errors; plugins/edge_add_remove: sort edge-indices on removal
  Justfile
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/test_fixtures/edge_add_remove_trigger_edge_index_error.json
  dist/cargo_test.sh
  graph-builder/tests/mod.rs
Labels: approved, lgtm

#257 tests/e2e: gate SLO tests with `test-e2e-slo` feature
  graph-builder/tests/mod.rs
Labels: approved, lgtm

#250 openshift_secondary_metadata_parser: add 20200319.204124 test fixtures
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/channel_filter.rs
  cincinnati/src/plugins/internal/edge_add_remove.rs
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/plugin.rs
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.1.1.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.1.10.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.2.0-rc.5.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.2.0.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.2.1.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.2.11-s390x.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.2.11.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.2.13-s390x.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.2.22.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.3.0-rc.0.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.3.0-rc.3.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.3.0.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.3.2.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.3.3.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/blocked-edges/4.3.5.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/candidate-4.2.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/candidate-4.3.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/candidate-4.4.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/candidate-4.5.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/fast-4.2.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/fast-4.3.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/fast-4.4.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/fast-4.5.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/prerelease-4.1.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/prerelease-4.2.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/stable-4.0.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/stable-4.1.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/stable-4.2.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/stable-4.3.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/stable-4.4.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/channels/stable-4.5.yaml
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/cincinnati-graph-data/raw/metadata.json
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/graph-gb-raw.json
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20200319.204124/graph-gb-with-quay-metadata.json
  cincinnati/src/plugins/internal/graph_builder/release.rs
  cincinnati/src/plugins/internal/graph_builder/release_scrape_dockerv2/plugin.rs
  cincinnati/src/plugins/internal/graph_builder/release_scrape_dockerv2/registry/network_tests.rs
  cincinnati/src/plugins/internal/metadata_fetch_quay.rs
  cincinnati/src/plugins/internal/node_remove.rs
Labels: approved, lgtm

#259 Adding the just command to get output of graph-builder
  docs/developer/developing.md
Labels: approved, lgtm

#258 Justfile: make running the graph-builder and e2e tests simpler
  Justfile
  docs/developer/developing.md
Labels: approved, lgtm

#249 Move e2e tests out of graph-builder, check SLO after load-testing
  Cargo.lock
  Cargo.toml
  dist/Dockerfile.e2e/Dockerfile
  dist/cargo_test.sh
  dist/pr_check.sh
  e2e/Cargo.toml
  e2e/e2e.rs
  e2e/tests/e2e.rs
  e2e/tests/prometheus_query.rs
  e2e/tests/slo.rs
  e2e/tests/testdata/a-amd64.json
  e2e/tests/testdata/b-amd64.json
  e2e/tests/testdata/test-amd64.json
  graph-builder/Cargo.toml
  graph-builder/tests/mod.rs
  graph-builder/tests/slo/mod.rs
  hack/e2e.sh
  hack/load-testing.sh
  hack/vegeta.targets
  prometheus-query/Cargo.toml
  prometheus-query/src/lib.rs
  prometheus-query/src/v1/mod.rs
  prometheus-query/src/v1/queries/instant.rs
  prometheus-query/src/v1/queries/mod.rs
Labels: approved, lgtm

#232 graph-builder: use openshift/cincinnati-graph-data instead of quay labels
  Cargo.lock
  Justfile
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/github_v3.rs
  cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/plugin.rs
  commons/src/lib.rs
  dist/Dockerfile.e2e/Dockerfile
  dist/openshift/cincinnati.yaml
  e2e/Cargo.toml
  e2e/tests/e2e.rs
  e2e/tests/testdata/a-amd64.json
  e2e/tests/testdata/b-amd64.json
  e2e/tests/testdata/d980578d2e9b1869b6b1e22711c68c03f0751974_stable-4.2_amd64-production.json
  e2e/tests/testdata/d980578d2e9b1869b6b1e22711c68c03f0751974_stable-4.2_s390x-production.json
  e2e/tests/testdata/d980578d2e9b1869b6b1e22711c68c03f0751974_stable-4.3_amd64-production.json
  e2e/tests/testdata/d980578d2e9b1869b6b1e22711c68c03f0751974_stable-4.3_s390x-production.json
  e2e/tests/testdata/metadata_revision
  e2e/tests/testdata/test-amd64.json
  graph-builder/Cargo.toml
  graph-builder/src/config/options.rs
  graph-builder/src/config/settings.rs
  hack/e2e.sh
  hack/load-testing.sh
  policy-engine/src/config/options.rs
Labels: approved, lgtm, size/L

#262 dist/openshift: configure oauth_token_path
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm
