Repository openshift/cincinnati, pull requests merged in 2020-01, with the labels that each got.

#191 Add scripts for upstream e2e tests
  dist/Dockerfile.e2e/Dockefile
  dist/openshift/cincinnati.yaml
  hack/e2e.sh
Labels: approved, lgtm, size/M

#192 Fix a typo in e2e filename
  dist/Dockerfile.e2e/Dockerfile
Labels: approved, lgtm, size/XS

#194 Add jottofar as approver
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#199 cincinnati: fix cargo fmt
  cincinnati/src/lib.rs
Labels: approved, lgtm, size/XS

#201 dist/Dockerfile.build/Dockerfile: use Rust 1.40.0
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm, size/XS

#200 e2e improvements
  dist/openshift/cincinnati.yaml
  hack/e2e.sh
Labels: approved, lgtm, size/M

#203 dist/Dockerfile.deploy/Dockerfile: install openssl
  dist/Dockerfile.deploy/Dockerfile
Labels: approved, lgtm, size/XS

#204 dist/Dockerfile.build/Dockerfile: Use Rust 1.41
  dist/Dockerfile.build/Dockerfile
Labels: approved, lgtm, size/XS

#202 e2e: add cargo-based e2e test and run it after the instance is stood up
  Cargo.lock
  graph-builder/Cargo.toml
  graph-builder/tests/e2e/mod.rs
  graph-builder/tests/e2e/testdata/a-amd64.json
  graph-builder/tests/e2e/testdata/b-amd64.json
  graph-builder/tests/e2e/testdata/test-amd64.json
  graph-builder/tests/mod.rs
  hack/e2e.sh
Labels: approved, lgtm, size/L
