Repository openshift/cincinnati, pull requests merged in 2021-01, with the labels that each got.

#354 Bug 1913442: Dockerfile.e2e: add rustfmt and yaml lint scripts
  dist/Dockerfile.e2e/Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#356 Bug 1913442: Adding yamllint to e2e Dockerfile
  dist/Dockerfile.e2e/Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#358 Bug 1915343: Moving to http://registry.centos.org/centos/centos:7
  dist/Dockerfile.build/Dockerfile
  dist/Dockerfile.deploy/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#359 Bug 1915751: e2e/tests/slo.rs: update graph_serve_duration_seconds test case
  e2e/tests/slo.rs
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#348 Bug 1915968: dkrv2_openshift_secondary_metadata_scraper: check signatures
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/plugins/internal/graph_builder/dkrv2_openshift_secondary_metadata_scraper/gpg.rs
  cincinnati/src/plugins/internal/graph_builder/dkrv2_openshift_secondary_metadata_scraper/mod.rs
  cincinnati/src/plugins/internal/graph_builder/dkrv2_openshift_secondary_metadata_scraper/plugin.rs
  cincinnati/src/plugins/internal/graph_builder/dkrv2_openshift_secondary_metadata_scraper/test_fixtures/public_keys/vrutkovs.asc
  cincinnati/src/plugins/internal/graph_builder/dkrv2_openshift_secondary_metadata_scraper/test_fixtures/signatures/message.json
  cincinnati/src/plugins/internal/graph_builder/dkrv2_openshift_secondary_metadata_scraper/test_fixtures/signatures/signature-3
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#363 Bug 1915343: dist/Dockerfile.build: optimize Dockerfile
  dist/Dockerfile.build/Dockerfile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#366 Bug 1916188: Dockerfile: remove extra copies
  dist/Dockerfile.deploy/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
  hack/e2e.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#367 Bug 1916188: Dockerfile.deploy: copy sourcecode
  dist/Dockerfile.deploy/Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
