Repository openshift/cincinnati, pull requests merged in 2022-08, with the labels that each got.

#711 add multi-arch images support
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/plugins/internal/graph_builder/release_scrape_dockerv2/registry/mod.rs
  docs/design/openshift.md
Labels: approved, lgtm

#724 redeploy cincinnati on configuration change
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm

#725 qcontract recycle annotation needs to be string
  dist/openshift/cincinnati.yaml
Labels: approved, lgtm

#727 dist/openshift: Declare group in Template apiVersion
  dist/openshift/cincinnati-e2e.yaml
  dist/openshift/cincinnati.yaml
  dist/openshift/observability.yaml
Labels: approved, lgtm

#730 OCPBUGS-179: fix conditional edge for type always
  cincinnati/src/conditional_edges.rs
  cincinnati/src/lib.rs
  cincinnati/src/plugins/external/web.rs
  cincinnati/src/plugins/mod.rs
  dist/Dockerfile.e2e-ubi8/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#719 fix e2e prometheus, operator-group, 4.11 errors
  dist/openshift/cincinnati-e2e.yaml
  hack/e2e.sh
Labels: approved, lgtm

#712 Bumping Rust version to 1.62.0
  dist/Dockerfile.deploy/Dockerfile
  dist/Dockerfile.e2e/Dockerfile
Labels: approved

#733 update grafana dashboard to include additional metrics
  dist/grafana/cincinnati-sli.json
  dist/grafana/dashboards/cincinnati-sli.configmap.yaml
Labels: approved, lgtm

#734 [grafana] fix data-sources for cluster queries
  dist/grafana/cincinnati-sli.json
  dist/grafana/dashboards/cincinnati-sli.configmap.yaml
Labels: approved, lgtm
