Repository openshift/cincinnati, pull requests merged in 2024-10, with the labels that each got.

#937 OTA-543: add autoscaler to cincinnati deployment
  dist/openshift/cincinnati-deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#944 OTA-1348: Fix typos in the metadata-helper unit tests
  metadata-helper/src/config/cli.rs
  metadata-helper/src/config/file.rs
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#945 OTA-1348: Improve the diff output in the `compare_graphs_verbose` function
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#946 OTA-1348: Increment `http_upstream_reqs` on errors
  cincinnati/src/plugins/internal/cincinnati_graph_fetch.rs
Labels: approved, lgtm, jira/valid-reference

#942 OTA-543: Add PrometheusRule to create a recording rule for calculating avg requests
  dist/openshift/cincinnati-deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#948 NO-JIRA: deps: remove unused `failure` dependency
  Cargo.lock
  cincinnati/Cargo.toml
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/plugin.rs
  cincinnati/src/plugins/mod.rs
  commons/src/errors.rs
  e2e/Cargo.toml
Labels: approved, lgtm, jira/valid-reference

#953 replace HPA with keda ScaledObject
  dist/openshift/cincinnati-deployment.yaml
Labels: approved, lgtm

#956 ScaledObject threshold value should be a string 'integer'
  dist/openshift/cincinnati-deployment.yaml
Labels: approved, lgtm

#950 OTA-1348: Fix the failing `compare_quay_result_fixture::_20211124_083150_` test
  cincinnati/src/lib.rs
  cincinnati/src/plugins/internal/graph_builder/openshift_secondary_metadata_parser/test_fixtures/20211124.083150/graph-gb-with-quay-metadata.json
Labels: approved, lgtm, jira/valid-reference

#967 bring back the replica field and set it to min-replicas
  dist/openshift/cincinnati-deployment.yaml
Labels: approved

#969 OTA-1378,OTA-1379: add retry logic for pulling images and less logs for sigs
  cincinnati/src/plugins/internal/graph_builder/release_scrape_dockerv2/registry/mod.rs
Labels: approved, lgtm, jira/valid-reference

#972 OTA-1382: dist/openshift: Set maxUnavailable:0 in Deployments
  dist/openshift/cinci-with-mh-deployment.yaml
  dist/openshift/cincinnati-deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#970 OTA-1348: Fix registry URL parser tests
  cincinnati/src/plugins/internal/graph_builder/release_scrape_dockerv2/registry/mod.rs
Labels: ¯\_(ツ)_/¯, approved, lgtm, jira/valid-reference
